// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Model
{
    [default_interface] runtimeclass ApplicationState {
        static ApplicationState SharedInstance();

        Boolean CloseAllTabsWarningDismissed;
        Boolean LargePasteWarningDismissed;
        Boolean MultiLinePasteWarningDismissed;
    }
}
